apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000        # inside cluster
      targetPort: 3000  # container port
      nodePort: 30080   # accessible on host VM